--계정생성
CREATE USER c##springboot IDENTIFIED BY springboot1234 
    DEFAULT TABLESPACE users 
    TEMPORARY TABLESPACE temp 
    PROFILE DEFAULT;
--권한부여    
GRANT CONNECT, RESOURCE TO c##springboot; 
GRANT CREATE VIEW, CREATE SYNONYM TO c##springboot; 
GRANT UNLIMITED TABLESPACE TO c##springboot; 
--락 풀기
ALTER USER c##springboot ACCOUNT UNLOCK;